type Pokemon {
  id: Int!
  name: String!
  type: String!
  created_at: String!
}

type PokemonAlreadyExistsError {
  message: String!
}

type PokemonNotFoundError {
  message: String!
}

input CreatePokemonInput {
  id: Int!
  name: String!
  type: String!
}

input UpdatePokemonInput {
  id: Int!
  name: String
  type: String
}

union CreatePokemonResult = Pokemon | PokemonAlreadyExistsError

type Query {
  pokemons: [Pokemon!]!
}

type Mutation {
  createPokemon(input: CreatePokemonInput!): CreatePokemonResult!
  updatePokemon(input: UpdatePokemonInput!): Pokemon!
  deletePokemon(id: Int!): Boolean!
}
